services:
  fastapi-gateway:
    build:
      context: .
    image: ios_app_backend
    container_name: ost_app_backend
    command: uvicorn backend.main:app --host 0.0.0.0 --port 8000 --reload
    ports:
      - "8001:8000"
    environment:
      - DATABASE_URL=postgresql://postgres:fDdiFw_KB2930otN@ost_postgres:5432/postgres
      - API_SECRET_KEY=your-api-key
      - ADMIN_PHONE=016441474
      - ADMIN_PASSWORD=reach1234
      - ADMIN_NAME=Admin Reach
    restart: always

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: ios_app_frontend
    container_name: ost_app_frontend
    ports:
      - "3000:80"
    depends_on:
      - fastapi-gateway
    restart: always
